### ISSUE TITLE
Add Go client and CLI commands for files API

### ISSUE THREAD

**Issue by tunahanertekin** [canonical/pebble#107]
Progress on this:

* [x] https://github.com/canonical/pebble/pull/143
* [x] https://github.com/canonical/pebble/pull/144
* [x] https://github.com/canonical/pebble/pull/146
* [x] https://github.com/canonical/pebble/pull/147
* [x] https://github.com/canonical/pebble/pull/148

For completeness, we need to Go back and implement the Go client and CLI commands for the files API. Our previously discussed approach to this is shown in the [spec](https://docs.google.com/document/d/1NPPZZB_qCwtTru-YsKkRSAb6mXJzBiE0fG3GTZnx4fM/edit#heading=h.1tsi183ijqx). See there for details, but in summary:

```
# Go client. For now, we're not proposing to support multi-file push/pull (same as Python client).
func (*Client) Pull(opts *PullOptions) (PushResult, error)
func (*Client) Push(opts *PushOptions) (PushResult, error)
func (*Client) ListFiles(opts *ListFilesOptions) (ListFilesResult, error)
func (*Client) MakeDir(opts *MakeDirOptions) (MakeDirResult, error)
func (*Client) RemovePath(opts *RemovePathOptions) (RemovePathResult, error)

# Pebble CLI.
pebble push file.txt /path [-m|--mode=644 --user=USER|uid --group=GROUP|gid]
pebble pull /path file.txt
pebble cat /path # same as pull, but write to stdout
pebble mkdir /path [-p|--parents -m|--mode=755 --user=USER|uid --group=GROUP|gid]
pebble rm /path [-r|--recursive]
pebble ls '/etc/*.conf'  # path can be dir, file, or glob
```

@tunahanertekin's original message:

> Hi there, Pebble's File API usage is explained [here](https://juju.is/docs/sdk/pebble#heading--the-files-api) when using it on Juju operator framework. Is there a way to use Pebble's File API on Golang? I've tried to find it in [Pebble's Go client](https://pkg.go.dev/github.com/canonical/pebble) but I couldn't.

**Comment by benhoyt** [comment]
Thanks, @tunahanertekin -- yeah, at this point we don't have a Go client or CLI commands for the files API (there's only the Python one as part of the Python Operator Framework). I'm going to update this issue to request adding that. We should have it for completeness, though we haven't needed it to date for Juju.

Out of interest, what's your use case, and what APIs specifically would be most important? Are you trying to write a Juju operator in Go?

**Comment by tunahanertekin** [comment]
> Thanks, @tunahanertekin -- yeah, at this point we don't have a Go client or CLI commands for the files API (there's only the Python one as part of the Python Operator Framework). I'm going to update this issue to request adding that. We should have it for completeness, though we haven't needed it to date for Juju.
> 
> Out of interest, what's your use case, and what APIs specifically would be most important? Are you trying to write a Juju operator in Go?

Thanks for your reply @benhoyt.

As robolaunch, our use case is to adapt ROS 2 and DDS domain to the Kubernetes environment and provide an open source solution for cloud robotics & simulation & fleet management. We're planning to develop our Kubernetes operators with Kubebuilder SDK and looking for methods to manage container processes. An additional motivation of ours is to expose some of the abilities of our container supervisor to CR.

Legacy methods like supervisord have other drawbacks such as it's native way to expose itself is XMLRPC. It seems that Pebble is the best fit for our use cases with it's flexibility and we do want to configure some parts of the filesystem directly using files API, not with ConfigMaps or Secrets. Also Container exec is a hard method to automate when reconciling, but configuring files with files API can easily be automated.

Additionally, being able to add new layers on runtime is an awesome feature of Pebble since it allows us to do dynamic configurations and seamless upgrades. If you have a suggestion or comment about our use case, we'll be glad to hear.

**Comment by benhoyt** [comment]
For reference, this is being worked on my @anpep.

**Comment by benhoyt** [comment]
This is all done now (and has been for a while), thanks @anpep!
