### ISSUE TITLE
Need a way to send signals to services (eg: SIGHUP to reload config)

### ISSUE THREAD

**Issue by mthaddon** [canonical/pebble#16]
Currently you can stop and start services using pebble, but it would be useful to have a way of reloading them for services that support that, to avoid service interruptions where possible.

I've also filed https://github.com/canonical/operator/issues/491 to enable this in the Operator Framework when it's available.

**Comment by benhoyt** [comment]
Will do this soon! This is described in spec [JU029](https://docs.google.com/document/d/1R9gdQU7q1CdH3raqLeB9d86pICbOSpm0P04P_CNF2g0/edit). Basically a simple API at `/v1/signals` to send a signal to the given services (and similar functionality in the Python Operator Framework).

**Comment by benhoyt** [comment]
Implemented in https://github.com/canonical/pebble/pull/92 (and will be included in the next version of Juju 2.9.x) and the Python Operator Framework side in https://github.com/canonical/operator/pull/669.
