### ISSUE TITLE
Intermittent failure in CheckersSuite.TestExec

### ISSUE THREAD

**Issue by barrettj12** [canonical/pebble#170]
There's an intermittent timeout with the following test:
CheckersSuite.TestExec
internal/overlord/checkstate/checkers_test.go:157

```
panic: test timed out after 10m0s
```

More details here:
https://github.com/canonical/pebble/actions/runs/3615562564/jobs/6092736968

**Comment by barrettj12** [comment]
Again: https://github.com/canonical/pebble/actions/runs/3929632318/jobs/6718672696

**Comment by benhoyt** [comment]
This has not surfaced for a looong time, and I'm redoing the checkstate package in #409 in any case -- closing. Can always open a new issue if something new surfaces.
