### ISSUE TITLE
Add option in pebble exec to inherit environment variables from caller's environment

### ISSUE THREAD

**Issue by averma-canonical** [canonical/pebble#172]
Request to add an option in pebble exec command to inherit environment variables from the caller's environment, much like the preserve-env option in sudo.

The use case is for pebble to execute a one-shot command as a non-root user inheriting all environment variables the rock has defined for the root user.

**Comment by niemeyer** [comment]
Unlike sudo, the thing being started is not a plain shell or a plain command, but rather a program that will carry its own environment and configuration, and in general will have an expectation of it being preserved. Blindly fiddling with this environment is likely to result in unexpected behavior.  For that kind of reason, even in applications such as ssh the client environment's won't be sent over transparently.

Can you provide some further details about what you intent to do with it?  Maybe there is some alternative.

**Comment by benhoyt** [comment]
See also the planned feature for exec (and exec-type health checks) we've called "context", which would allow you to run commands in the context of another service, or of Pebble itself:

* https://github.com/canonical/pebble/issues/159 -- feature issue
* https://github.com/canonical/pebble/issues/125 -- previous discussion

Would `--context=pebble`, or similar, work for you? As Gustavo mentioned, it would also be good to know more about your specific use case.

**Comment by benhoyt** [comment]
@averma-canonical Thanks for that description. It seems to me that the addition of `--context=pebble` (or `--context=-` or whatever syntax we give it) would solve your problem, right? That would mean run with the same environment variables as Pebble was started with.

**Comment by averma-canonical** [comment]
Thanks @benhoyt. Yes that is exactly what we need.

**Comment by benhoyt** [comment]
Thanks. In that case I'll close this issue in favour of the existing #159.
