### ISSUE TITLE
Pebble does not perform variable expansion when executing commands

### ISSUE THREAD

**Issue by shayancanonical** [canonical/pebble#187]
# Issue
Pebble does not perform variable expansion when executing commands. The following show an unsuccessful variable expansion:

```
root@mysql-k8s-0:/# /charm/bin/pebble exec --env SOME_VAR=16 echo $SOME_VAR
root@mysql-k8s-0:/# /charm/bin/pebble exec --env SOME_VAR=16 echo '$SOME_VAR'
$SOME_VAR
root@mysql-k8s-0:/# /charm/bin/pebble exec --env SOME_VAR=16 echo "$SOME_VAR"

root@mysql-k8s-0:
```

To successfully access the defined env var, we need to use a shell to do so:
```
root@mysql-k8s-0:/# /charm/bin/pebble exec --env SOME_VAR=16 -- sh -c 'echo $SOME_VAR'
16
root@mysql-k8s-0:/#
```

**Comment by benhoyt** [comment]
Yes, this is by design. The exec command is a plain command line, not executed via the shell. Similar to the `command: ...` field of services -- these are also executed directly, not via the shell. See "not interpreted by a shell" under https://github.com/canonical/pebble/#layer-specification
