### ISSUE TITLE
Protect against nonexistent user home directories when running pebble exec as a user

### ISSUE THREAD

**Issue by shayancanonical** [canonical/pebble#189]
# Issue

When one runs `useradd <user>` to create a user, the home directory for the user is not guaranteed to be created. The following is a statement from the [man page of useradd](https://linux.die.net/man/8/useradd):
> d, --home HOME_DIR
    The new user will be created using HOME_DIR as the value for the user's login directory. The default is to append the LOGIN name to BASE_DIR and use that as the login directory name. The directory HOME_DIR does not have to exist but will not be created if it is missing.

Despite this missing home directory, one can sign in as the user and execute commands (albeit with a warning displayed):
```
root@mysql-k8s-0:/# su - mysql 
su: warning: cannot change directory to /home/mysql: No such file or directory
$ pwd 
/
```

However, (and may be due to the warning), running `pebble exec` with such a user fails:
```
root@mysql-k8s-1:/# /charm/bin/pebble exec --user mysql --group mysql pwd
error: cannot perform the following tasks:
- exec command "pwd" (fork/exec /usr/bin/pwd: no such file or directory)
```

**Comment by shayancanonical** [comment]
@jameinel I confirmed that `/usr/bin/pwd` is present in the container:

```
root@mysql-k8s-0:/# cat /etc/passwd | grep mysql
mysql:x:999:999::/nonexistent:/bin/sh
root@mysql-k8s-0:/# /charm/bin/pebble exec --user mysql --group mysql /usr/bin/pwd
error: cannot perform the following tasks:
- exec command "/usr/bin/pwd" (fork/exec /usr/bin/pwd: no such file or directory)
root@mysql-k8s-0:/# usermod -d /home/mysql/ mysql
root@mysql-k8s-0:/# cat /etc/passwd | grep mysql
mysql:x:999:999::/home/mysql/:/bin/sh
root@mysql-k8s-0:/# /charm/bin/pebble exec --user mysql --group mysql /usr/bin/pwd
/home/mysql
```

could it be possible that there's a typo in the 2nd code block you pasted (`pwdd` instead of `pwd`)?

**Comment by benhoyt** [comment]
@shayancanonical I've addressed this in https://github.com/canonical/pebble/pull/309. Initially I fixed it so that it wouldn't fail in this scenario (and use the default directory "/" instead). However, that's problematic -- read the PR description there for updates and workaround and let me know if you think this is reasonable.
