### ISSUE TITLE
Log flood: Pebble dumps 37485 log lines in 2 seconds: "Cannot abort stop for service"

### ISSUE THREAD

**Issue by sed-i** [canonical/pebble#211]
I'm running a load test for COS Lite, and every 4 hours prometheus is killed (`StopContainer`; haven't figured out yet why) and pebble log-floods (37485 log lines in 7 seconds; more like in 2 seconds if we look at the original timestamps):

```bash
$ journalctl | grep "Cannot abort stop for service" | grep "19:00:" | sed -n -e '1p;$p'
Apr 06 19:00:31 pd-ssd-4cpu-8gb kubectl[546799]: 2023-04-06T23:00:31.332Z [pebble] Cannot abort stop for service "prometheus", signals already sent
Apr 06 19:00:38 pd-ssd-4cpu-8gb kubectl[546799]: 2023-04-06T23:00:33.405Z [pebble] Cannot abort stop for service "prometheus", signals already sent

$ journalctl | grep "Cannot abort stop for service" | grep "19:00:" | wc -l
37485
```

**Comment by benhoyt** [comment]
Hi @sed-i, can you provide any more details here? For example, the Pebble plan, or other context, for example logs above what's shown? Could you re-run with `PEBBLE_DEBUG=1` for additional debugging logs.

This must be the result of a "stop" operation -- either a manual call to stop (eg: `pebble stop`) or the automatic stop of all services done during Pebble shutdown. I'm guessing the latter, given that you say this is occurring after StopContainer, which is presumably shutting down Pebble and the whole container.

I'm not yet sure what's causing the abort of the log flood. Maybe if the service fails to stop within the shutdown timeout this happens (I'll test that later).

**Comment by sed-i** [comment]
Per discussion, couldn't reproduce [that log line](https://github.com/canonical/pebble/blob/d79e84f6be22c4d9165da82bdb7792277395aebd/internals/overlord/servstate/handlers.go#L250) with:
```bash
juju ssh --container prometheus prometheus/0 'bash -c "pebble stop prometheus & disown; sleep 0.1; pkill pebble"'
```
with sleep times between 0 and 0.2.
Closing for now.
