### ISSUE TITLE
Gorilla toolkit (mux/websocket) is in archive mode

### ISSUE THREAD

**Issue by SimonRichardson** [canonical/pebble#219]
The [gorilla tookit](https://github.com/gorilla#gorilla-toolkit) which includes mux and websocket is no longer being actively maintained, which also includes any security updates as the projects are only in "read-only" mode.

**Comment by benhoyt** [comment]
Understood -- thanks for opening this issue. I don't think it's particularly critical (unless we find that gorilla/mux has a gaping security hole we need to fix). When we do fix it we should probably just use a simple [regex table](https://benhoyt.com/writings/go-routing/#regex-table) approach to avoid the 3rd party dependency altogether.

**Comment by SimonRichardson** [comment]
Agreed, I did end up reading your blog post to see if there was a viable alternative (the easy answer was yes) the other day.

**Comment by benhoyt** [comment]
Gorilla has now come back out of maintenance mode and has been unarchived. A group of maintainers from Redhat took over: https://github.com/orgs/gorilla/discussions/9
