### ISSUE TITLE
Use entrypoint of a Docker Image as default Command

### ISSUE THREAD

**Issue by DomFleischmann** [canonical/pebble#22]
Currently if you want to start a container through Pebble you will have to provide the command to start the container in the `command` field.

This command seems to be equivalent to the ENTRYPOINT field of a Dockerfile, for example.

In the case of a container definition in a Pod in Kubernetes the `command` field is optional and will default to the entrypoint if none is stated. Similar default behavior in Pebble would make sense. Additionally an `arguments` field to expand the entrypoint would also be very useful, for further configuration.

More context on how this is done in Kubernetes: https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/

Use case of a pod_spec charm where no `command` option is provided, but a `argument` option is: https://github.com/charmed-kubernetes/kubernetes-dashboard-operator/blob/main/charms/kubernetes-dashboard/src/charm.py#L79

**Comment by Abuelodelanada** [comment]
> Currently if you want to start a container through Pebble you will have to provide the command to start the container in the `command` field.
> 
> This command seems to be equivalent to the ENTRYPOINT field of a Dockerfile, for example.

Seems to be equivalent but, so far [I am having a different result](https://github.com/canonical/mysql-operator/pull/44#issuecomment-832387939) than using pod_specs.

**Comment by niemeyer** [comment]
This issue must be filed against juju. Pebble has no idea it's even running inside a container, and there's no way for it to ask its environment about what args or commands it's supposed to run with.

There's an issue related to this feature that makes sense for Pebble, though, in terms of organization of commands and arguments, but that's not about Docker or entrypoints.

**Comment by mmanciop** [comment]
Bug filed against Juju: https://bugs.launchpad.net/juju/+bug/1929861
