### ISSUE TITLE
Make layer labels starting with the "pebble-" prefix reserved

### ISSUE THREAD

**Issue by rebornplusplus** [canonical/pebble#220]
Following the discussions from https://github.com/canonical/pebble/pull/191#discussion_r1183910905, consider making any layer labels starting with the `pebble-` prefix reserved.

**Comment by barrettj12** [comment]
@aliamerj easy one for you to start on

**Comment by aliamerj** [comment]
Hello, i am working on this issue , i just need some clarification 
- Could you please provide more details on what "reserving" labels with "pebble-" prefix entails? Are we preventing users from creating such labels? Or is it about some internal logic?

- Scope: Is the reservation of "pebble-" prefixed labels only applicable to certain parts of the Pebble system, or is it universally across all features?

- Case Sensitivity: Is the "pebble-" prefix case-sensitive? Should I treat "Pebble-" the same as "pebble-" when implementing this feature?

**Comment by barrettj12** [comment]
Hi @aliamerj, reserving the label means the user shouldn't be able to create a layer with that label. i.e. label names of the form `nnn-pebble-*` are disallowed.

There is currently code in the plan package which checks for e.g. reserved service names - just add a check for reserved labels, and a corresponding unit test.

I think just handle the lowercase version `pebble-`, don't worry about other cases.
