### ISSUE TITLE
Binaries created with "go install" don't include version number

### ISSUE THREAD

**Issue by benhoyt** [canonical/pebble#225]
The official binaries attached to a release (for example, [v1.2.0](https://github.com/canonical/pebble/releases/tag/v1.2.0)) know their own version as expected, however, a binary created with `go install` or `go run` does not. For example:

```
$ ~/Downloads/pebble_v1.2.0_linux_amd64/pebble version --client
v1.2.0
$ go install github.com/canonical/pebble/cmd/pebble@v1.2.0
$ pebble version --client
unknown
```

This is not ideal. It's happening because we generate but don't commit the generated version number. (Currently `cmd/version_generated.go` is in `.gitignore`.) Should we commit the generated version? Or is there a clever way to get the go-installed tag in there?

Relatedly, the Juju project builds Pebble from source and so the version of Pebble included in Juju says "unknown" when you do `pebble version --client` too. It's essentially the same issue. See further discussion at #212.

**Comment by benhoyt** [comment]
Might be able to use the new BuildInfo stuff for this. From https://blog.carlmjohnson.net/post/2023/golang-git-hash-how-to/:

> when you install a remote Go binary using go install example.com/cmd/sometool@v1.2.3, it won’t have any version control information, since it was downloaded and built from Go modules, and not from a version control system. In those cases, you can instead read the BuildInfo.Main.Version which will have the Git tag that was used to publish as a Go module.

**Comment by benhoyt** [comment]
We discussed this briefly with Gustavo and Harry a while back, and we want the version number committed in the source code of the released tag to make this work well. However, we want to be a bit careful about how we do this -- Harry had an idea for doing this on the version branch with a "negative commit", but I forget the details. @hpidcock Can you please clarify?

**Comment by hpidcock** [comment]
```
main -------- a       c -----
                \   /
tags/v1.2.3       b
```

a. cmd/version.go Version=unknown
b. cmd/version.go Version=1.2.3
c. cmd/version.go Version=unknown

**Comment by benhoyt** [comment]
After discussion, another way of showing that:

```
master: ---> a ---> b ---> c ---> c'
                           |
                           |
tags:                   v1.2.3
```

- a: feature 1
- b: feature 2
- c: set `Version = "v1.2.3"` in cmd/version.go
- c': set `Version = "unknown"` in cmd/version.go (reverts `c`)

And you'd push `c` and `c'` together to avoid GitHub having an in-between state up there.

We could also have the master branch say `Version = "v1.3.0-dev"` so you at least know which major+minor version you're dealing with when you check out the source code. See https://go.dev/doc/modules/version-numbers#pre-release

Before this is automated, probably worth doing a 1-page spec and get agreement on it.

**Comment by jnsgruk** [comment]
We could adopt the fairly common pattern of using `-X` during the build to set the version ... example here:

https://github.com/jnsgruk/releasegen/blob/9d2cf69d556e67d17ed4ec13b0d12d917aaf4d26/main.go#L11

And the corresponding build flags:

https://github.com/jnsgruk/releasegen/blob/9d2cf69d556e67d17ed4ec13b0d12d917aaf4d26/.goreleaser.yaml#L14

**Comment by benhoyt** [comment]
Just a note that I did this manually for the [v1.3.0](https://github.com/canonical/pebble/releases/tag/v1.3.0) release, so this works fine for that release (though we'll want to automate this):

```
$ go install github.com/canonical/pebble/cmd/pebble@v1.3.0
go: downloading github.com/canonical/pebble v1.3.0
$ pebble version --client
v1.3.0
```

**Comment by benhoyt** [comment]
Just a note for future reference: pushing both the version commit and the revert commit in the same push event confused the store snap builder, and @cjdcordeiro had to fix it up manually. So when we automate this we should probably do it in two push events (with a delay?) or ask the store team to fix this logic.

**Comment by benhoyt** [comment]
This issue is fixed, as we now just modify `cmd/version.go` and hard-code the version number. We have a semi-automated releases process (it's all automated, including Snap builds, except for updating the version file). This is not onerous and seems fine for now, so closing this issue. We've also updated the [docs with the steps for creating a release](https://github.com/canonical/pebble/blob/master/HACKING.md#creating-a-release).
