### ISSUE TITLE
Environments should be a plain dictionary

### ISSUE THREAD

**Issue by niemeyer** [canonical/pebble#23]
I was the one proposing it as a list, mainly because if we want to use interpolation of variables we need to know the order to take place. With that said, looking at code in the wild that has a list of Python dictionaries inside a Python list inside a Python dict, made me cringe a bit, and I fear we'll regret that decision, which soon cannot be undone once 2.9 is out.

As such, I suggest some quick action on our end to undo that both in the operator and in pebble, so that becomes just a plain map (dict) everywhere.

To solve the ordering issue, we can do a slightly more complex explicit dependency check across the strings, to make sure that the ordering is right and to prevent clients having to deal with unusual ordered dictionaries.

How does that sound, @benhoyt?

**Comment by benhoyt** [comment]
Yeah, I agree that's going to be much nicer for the Charm author. And it won't be hard for us to use `os.Expand` with a custom mapper to build a list of the dependencies, and then run `Expand` again in the right order.

I'll put a Pebble and an Operator Framework PR -- probably today.

**Comment by benhoyt** [comment]
This is done now, and will be included in Juju 2.9-rc8 (coming out today or tomorrow).
