### ISSUE TITLE
Misleading error message in container.exec

### ISSUE THREAD

**Issue by omar-selo** [canonical/pebble#235]
When running the following code:
```python
self.container = self.unit.get_container("mycontainer")
self.container.exec(["realcommand"], working_dir="/path/that/doesnt/exist")
stdout, stderr = process.wait_output()
if stderr:
    logger.error(stderr)
logger.info(stdout)
```

It returns the following error:
```
fork/exec /usr/local/bin/realcommand: no such file or directory
```

This error is very misleading. `/usr/local/bin/realcommand` does exist. What doesn't exist is `/path/that/doesnt/exist` that was set as `working_dir` of exec call.

Note: this is the original conversation on charmhub mattermost https://chat.charmhub.io/charmhub/pl/b16f95fnt7rmugynwfg5sjbo7a

**Comment by benhoyt** [comment]
Thanks for the report -- improving this in #236.

**Comment by benhoyt** [comment]
@omar-selo Note that this is fixed, however, it will only trickle down to Juju once we update the Pebble version used in Juju and ship a new Juju version, so that might be a few weeks away yet.
