### ISSUE TITLE
'pebble run CUSTOMDIR'

### ISSUE THREAD

**Issue by jameinel** [canonical/pebble#26]
This is a feature request to support instantiating a pebble instance to a custom directory, rather than /var/lib/pebble/default.
This is mostly to make it easy to test against pebble, without having it actually as PID 1.

I guess you can `export PEBBLE=$HOME/test`, so maybe that should just be documented as part of `pebble run` help text?

**Comment by benhoyt** [comment]
@jameinel This is documented at https://github.com/canonical/pebble#general-model -- does that work for you?
