### ISSUE TITLE
Data race in `internals/overlord/servstate:S.startTestServices(c)`

### ISSUE THREAD

**Issue by barrettj12** [canonical/pebble#264]
This is a utility function called in many of the servstate tests.
https://github.com/canonical/pebble/blob/00bcd1f7dda570bcdf42600545ddc1707d24365e/internals/overlord/servstate/manager_test.go#L256

It starts two services
- `test1`: `/bin/sh -c "echo test1 | tee -a .../log.txt; sleep 10"`
- `test2`: `/bin/sh -c "echo test2 | tee -a .../log.txt; sleep 10"`

and then asserts the contents of `log.txt` are
```
test1
test2
```

However, there is a data race, since we may read `log.txt` before the `test2` service has had a chance to write to it.

```
manager_test.go:203:
    c.Assert(string(data), Matches, "(?s)"+expected)
... value string = "test1\n"
... regex string = "" +
...     "(?s).*test1\n" +
...     ".*test2\n"
```

### To reproduce

Create a new test in `internals/overlord/servstate/manager_test.go`:
```go
func (s *S) TestStartTestServices(c *C) {
	s.startTestServices(c)
}
```

Install the [`stress`](https://pkg.go.dev/golang.org/x/tools/cmd/stress) utility (useful for finding sporadic test failures):
```
go install golang.org/x/tools/cmd/stress@latest
```

Run
```
stress go test ./internals/overlord/servstate -check.f TestStartTestServices -count=1
```
and start observing failures.

**Comment by flotter** [comment]
I will add this to https://github.com/canonical/pebble/pull/266 - its not included right now, but easy to add.

**Comment by flotter** [comment]
https://github.com/canonical/pebble/pull/266 Should now fix this.
