### ISSUE TITLE
Windows and Darwin 

### ISSUE THREAD

**Issue by gedw99** [canonical/pebble#268]
This reminds me of overmind and Goreman. They are procfile runners in golang 

Overmind relies on tmux.
Goreman is able to run on windows.

Does pebble support windows or Darwin? I presume the unix domain sockets might be the blocker for windows ?

thanks for this interesting project !

**Comment by gedw99** [comment]
I am adding the link to cross OS socket ( named pipes etc), or reference

**Comment by benhoyt** [comment]
Hi @gedw99! Unfortunately Pebble only supports Linux right now. The daemon/server definitely has a hard requirement on Linux (yeah, Unix sockets, and a few others things). It might not be too hard to get the client working on non-Linux OSs, but there's probably not much appetite to make the daemon support non-Linux within Canonical. Fork away, though! :-)
