### ISSUE TITLE
Daemon / Reaper challenges

### ISSUE THREAD

**Issue by flotter** [canonical/pebble#284]
Currently, if I run:

```
flotter@pc:~/pebble/internals/daemon$ ./daemon.test -check.f TestRebootHelper -check.vv
START: daemon_test.go:751: daemonSuite.TestRebootHelper
START: daemon_test.go:61: daemonSuite.SetUpTest
PASS: daemon_test.go:61: daemonSuite.SetUpTest	0.001s

using shellcheck: "/usr/bin/shellcheck"
START: daemon_test.go:70: daemonSuite.TearDownTest
PASS: daemon_test.go:70: daemonSuite.TearDownTest	0.000s

... Panic: internal error: reaper must be started (PC=0x46F382)
```
This issue only happens when a subset of some tests are run.

The reason for this is because when the full suite is run, reapers started in some tests (e.g. ```TestAddRoutes```) **leak** into the following tests (this is a separate issue we need to clean up). For the daemon, the reaper is started when ```daemon.New(...)``` is called (indirectly when ```overlord.New``` create a new ```servstate``` manager). The reaper is killed when ```daemon.Stop(...)``` is called.

We have a much bigger issue here, which @benhoyt discovered, which is the current ```shutdown``` implementation in the daemon does not use the reaper, but calls ```exec.Command(...).CombinedOutput()``` directly. This means that the shutdown command will cause a ```wait()``` to reap the shutdown command on termination. This is in addition to the reaper, which will also receive a SIGCHILD and there will be a race who reaps the ```shutdown``` command.

Currently the ```shutdownHandler``` can be called while the reaper is active, and after the ```daemon.Stop()``` stopped the ```overlord``` where ```servstate.Stop()``` will kill the reaper. However the most common case today is likely as the final command in ```daemon.Stop()```, at which point the reaper will be dead.

One thing to note is that currently the reaper is owned by servstate. However, this is slightly misleading, because ```PR_SET_CHILD_SUBREAPER``` is a process level directive, so applies to the entire pebble, not only servstate. 

I have a proposal that I would like to get some feedback on:

1. Can we move the reaper right to the top so that the ```pebble run``` environment has this enabled for the entire process lifecycle?
2. Only use the reaper to run commands (this may require us to adapt ```systemd.go``` later on), which for now only means moving the ```shutdown``` call over to the reaper?
3. Have the daemon and overlord related test suites get the reaper enabled and disabled with each test, and only use ```FakeCommand``` with shellcheck running in reaper mode?

I think that the reaper is in all respects the better solution we have right now (preventing zombies from taking over our kernel process tables for long running setups) when running commands, and I see no downside from simply making this our preferred method to run and test with.

@benhoyt @barrettj12 @anpep Please let me know if you agree with the issue, and which way forward you would prefer ?

**Comment by benhoyt** [comment]
Yeah, very good analysis. I fully agree. I felt dirty putting `reaper.Start` into `servstate.NewManager` in the first place, but it's caused more issues than I expected. `git blame -> `benhoyt`. :-)

Please go ahead and make this change. Were you thinking `reaper.Start` / `reaper.Stop` would be in `daemon.Start` / `daemon.Stop`, or in the top-level run command handler? The daemon is basically process-global -- that seems a bit nicer than the caller having to do it when it's required by the daemon.

**Comment by flotter** [comment]
To further support this proposal:

Below is a test run where pebble received a SIGINT very quickly after startup. This is showing an interesting race between autostart and servstate shutdown, which kills the reaper. I need to fully investigate this, but moving the reaper out of servstate to a process level entity will also solve this.

flotter@pc:~/pebble$ 2023-09-28T12:02:11.993Z [pebble] Service "srv1" starting: sh -c  "while [ true ]; do echo .; sleep 1; done"
2023-09-28T12:02:11.996Z [pebble] POST /v1/services 6.401669ms 202
2023-09-28T12:02:11.996Z [pebble] Started default services with change 37.
2023-09-28T12:02:11.996Z [pebble] Exiting on terminated signal.
2023-09-28T12:02:12.007Z [pebble] Service "srv1" starting: sh -c  "while [ true ]; do echo .; sleep 1; done"
panic: internal error: reaper must be started

goroutine 66 [running]:
github.com/canonical/pebble/internals/reaper.StartCommand(0xc00057c160)
	/home/flotter/pebble/internals/reaper/reaper.go:164 +0x20f
github.com/canonical/pebble/internals/overlord/servstate.(*serviceData).startInternal(0xc000522480)
	/home/flotter/pebble/internals/overlord/servstate/handlers.go:435 +0xa66
github.com/canonical/pebble/internals/overlord/servstate.(*serviceData).start(0xc000522480)
	/home/flotter/pebble/internals/overlord/servstate/handlers.go:328 +0xc5
github.com/canonical/pebble/internals/overlord/servstate.(*ServiceManager).doStart(0xc0002060a0, 0xc000059df8?, 0xc000516000)
	/home/flotter/pebble/internals/overlord/servstate/handlers.go:133 +0x225
github.com/canonical/pebble/internals/overlord/state.(*TaskRunner).run.func1()
	/home/flotter/pebble/internals/overlord/state/taskrunner.go:195 +0xb4
gopkg.in/tomb%2ev2.(*Tomb).run(0xc000516000, 0x0?)
	/home/flotter/go/pkg/mod/gopkg.in/tomb.v2@v2.0.0-20161208151619-d5d1b5820637/tomb.go:163 +0x36
created by gopkg.in/tomb%2ev2.(*Tomb).Go
	/home/flotter/go/pkg/mod/gopkg.in/tomb.v2@v2.0.0-20161208151619-d5d1b5820637/tomb.go:159 +0xee
46ms
