### ISSUE TITLE
Linting is too slow

### ISSUE THREAD

**Issue by paul-rodriguez** [canonical/pebble#286]
Side note, but I don't understand why on earth doing a bit of static checking on a small project like Pebble would take 5 minutes! That's ~300 billion clock cycles. Do we know which of the static checkers is the culprit / why it's slow?

_Originally posted by @benhoyt in https://github.com/canonical/pebble/pull/273#discussion_r1302283424_

**Comment by flotter** [comment]
Just a note to others that currently this [PR](https://github.com/canonical/pebble/pull/267) will fix this, when merged.

**Comment by benhoyt** [comment]
@flotter How will that PR fix the slowness? Isn't that just bumping up the golangci timeout to 5 minutes (from the default of 1 minute)?

**Comment by benhoyt** [comment]
Going to close this. Linting locally takes <1s (even with a clean golangci-lint cache), and it's taking about 20s in CI now. Which is still way longer than expected, but I don't thin it's worth looking into further at this point.
