### ISSUE TITLE
Failing to build snap

### ISSUE THREAD

**Issue by flotter** [canonical/pebble#287]
11s
##[debug]Evaluating condition for step: 'Build Pebble Snap'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Build Pebble Snap
##[debug]Loading inputs
##[debug]Loading env
Run snapcore/action-build@v[1](https://github.com/canonical/pebble/actions/runs/5963122687/job/16190238156?pr=273#step:3:1)
  with:
    path: .
    build-info: true
    snapcraft-channel: stable
  env:
    SNAP_NAME: pebble
Building Snapcraft project in "."...
::group::Installing Snapcraft plus dependencies
Installing Snapcraft plus dependencies
  Ensuring runner is in the lxd group...
  /usr/bin/sudo groupadd --force --system lxd
  /usr/bin/sudo usermod --append --groups lxd runner
  Installing LXD...
  /usr/bin/sudo snap refresh lxd
  snap "lxd" has no updates available
  Initialising LXD...
  /usr/bin/sudo lxd init --auto
  Error: The process '/usr/bin/dpkg' failed with exit code 1
  ##[debug]Node Action run completed with exit code 1
  ##[debug]Finishing: Build Pebble Snap

**Comment by flotter** [comment]
@cjdcordeiro Not sure if this is a transient issue, but we seem to be failing consistently on this.

**Comment by flotter** [comment]
https://github.com/canonical/pebble/pull/285
https://github.com/canonical/pebble/pull/273

**Comment by flotter** [comment]
Will dive into this tomorrow.

**Comment by cjdcordeiro** [comment]
@flotter yes this seems to be a recent issue that affected many self-hosted runners.

I believe [this](https://github.com/snapcore/action-build/pull/59) should fix it. And I can see the last two snap workflows running successfully.

**Comment by flotter** [comment]
Thank you @cjdcordeiro, as you suggested the tests now pass. Thanks for the quick tip.
