### ISSUE TITLE
Cannot find current boot ID error on Google Cloud Run

### ISSUE THREAD

**Issue by gruyaume** [canonical/pebble#317]
### Bug Description

I'm trying to run a rockcraft build ROCK with a pebble service on Google Cloud Run and I'm getting the following error:

```shell
cannot run pebble: fatal: cannot find current boot ID: open /proc/sys/kernel/random/boot_id: no such file or directory
```

### To Reproduce

1. Create a Cloud Run service with the following container image: northamerica-northeast1-docker.pkg.dev/cognitive-profile/containers/cognitive-profile:0.1.0

_Note: You may not be able to reproduce with this specific image without the necessary registry permissions._

### Environment

- Run environment: Google Cloud Run
- Rockcraft: rockcraft (edge) 0+git.cc7e3af
- Pebble: v1.3.0

**Comment by gruyaume** [comment]
I initially created this issue in rockcraft but moved it over here since it looked pebble related.

**Comment by benhoyt** [comment]
It looks like Pebble reads `/proc/sys/kernel/random/boot_id` on startup to fetch the unique boot ID, and fails hard if it can't read that. That proc file is [documented here](https://docs.kernel.org/admin-guide/sysctl/kernel.html#random) as part of the Linux kernel docs, so I would have thought any Linux kernel would have that file -- I'm not sure what kernel version it was added in, though. What is the base image here, and what kernel and kernel version is it using? It might help if we could see your `rockcraft.yaml`.

**Comment by gruyaume** [comment]
You can see the rockcraft.yaml here:
- https://github.com/gruyaume/cognitive-profile/blob/main/rockcraft.yaml

Cloud Run is Google Cloud's serverless offering so I have no idea what kernel is behind it

**Comment by gruyaume** [comment]
I've just seen this post about Cloud Run's execution environment, I'll try running the ROCK with the second env instead of the default one: https://cloud.google.com/run/docs/about-execution-environments

**Comment by gruyaume** [comment]
Indeed, using the "second environment" solves the issue.

**Comment by benhoyt** [comment]
Excellent, good find and link. Closing this issue for now then.
