### ISSUE TITLE
Can't monitor if an async request to /v1/services has actually succeded

### ISSUE THREAD

**Issue by r00ta** [canonical/pebble#408]
Hey there, 

In MAAS we faced an [interesting bug](https://bugs.launchpad.net/maas/+bug/2060172). Basically: 

1) Pebble starts the Region (i.e. the kind of main process that configures all the others)
2) The region asks pebble to start NGINX with a `POST /v1/services` `{'action': 'start', 'services': ['http']}`
3) The region writes the NGINX configuration and asks pebble to restart NGINX (with a `POST /v1/services` `{'action': 'restart', 'services': ['http']}`)
4) pebble accepts the request and returns 202. The region does not try to restart NGINX anymore.
5) pebble refuses to restart NGINX because it is in the "Starting" status 
```
[change 3 "Stop service \"http\"" task] failed: cannot stop service while starting
```
And looking at https://github.com/canonical/pebble/blob/18c93cbc280de20c9e21d323fe3a8bbb340777a2/internals/overlord/servstate/handlers.go#L701 
6) NGINX is never restarted and it keeps using the old configuration (i.e. does not process the requests correctly).

My question is: since a request to `/v1/services` is processed asynchronously, how can we actually monitor that such request have completed successfully? If there is currently no way to do it, would it be possible to add a kind of `operationId` in the response headers so that we can then query pebble for the status of such request? This is sometimes referenced as [Long operation pattern](https://github.com/microsoft/api-guidelines/blob/vNext/azure/ConsiderationsForServiceDesign.md#long-running-operations) - used by [LXD](https://documentation.ubuntu.com/lxd/en/latest/rest-api/#asynchronous-operations) for example. 

Thanks!

**Comment by bjornt** [comment]
Also, something to consider is that pebble's main purpose is to handle services. Maybe it would make sense for pebble to be a bit smarter. So instead of simply failing to stop the service that is starting, maybe it should be smart enough to wait until it can start the service?

The alternative is to let every user of pebble having that logic. Having the logic in one central place might be better and more user friendly?

**Comment by benhoyt** [comment]
Are you able to use the get-change or wait-change API? (Sorry, our API is not officially documented yet -- that will hopefully change next cycle.) Whenever you call start/stop/restart/replan, Pebble returns a change ID that you can poll with [`/v1/changes/{changeID}`](https://github.com/canonical/pebble/blob/18c93cbc280de20c9e21d323fe3a8bbb340777a2/internals/daemon/api_changes.go#L173) or wait for with [`/v1/changes/{changeID}/wait`](https://github.com/canonical/pebble/blob/18c93cbc280de20c9e21d323fe3a8bbb340777a2/internals/daemon/api_changes.go#L186).

That's actually what the Pebble CLI commands like `pebble start` and similar do: they submit the request, look at the change ID and then poll quickly for the change to go "ready: true".

Here's an example of restarting a service and polling the get-change API using `curl`:

```
$ curl --unix-socket ~/pebble/.pebble.socket 'http://x/v1/services' \
       --request POST --data '{"action":"restart","services":["svc1"]}' | jq
{
  "type": "async",
  "status-code": 202,
  "status": "Accepted",
  "change": "67",  # <---- This is the change ID
  "result": null
}

$ curl --unix-socket ~/pebble/.pebble.socket 'http://x/v1/changes/67' | jq
{
  "type": "sync",
  "status-code": 200,
  "status": "OK",
  "result": {
    "id": "67",
    "kind": "restart",
    "summary": "Restart service \"svc1\"",
    "status": "Done",
    "tasks": [
      {
        "id": "88",
        "kind": "stop",
        "summary": "Stop service \"svc1\"",
        "status": "Done",
        "progress": {
          "label": "",
          "done": 1,
          "total": 1
        },
        "spawn-time": "2024-04-10T10:39:53.280030955+12:00",
        "ready-time": "2024-04-10T10:39:53.322018317+12:00"
      },
      {
        "id": "89",
        "kind": "start",
        "summary": "Start service \"svc1\"",
        "status": "Done",
        "progress": {
          "label": "",
          "done": 1,
          "total": 1
        },
        "spawn-time": "2024-04-10T10:39:53.280039783+12:00",
        "ready-time": "2024-04-10T10:39:54.357024735+12:00"
      }
    ],
    "ready": true,
    "spawn-time": "2024-04-10T10:39:53.280043347+12:00",
    "ready-time": "2024-04-10T10:39:54.357032061+12:00"
  }
}
```

Are you calling the Pebble API directly from Python? You could do something similar to [what we do in the Ops Pebble client](https://github.com/canonical/operator/blob/b7e5ba33e7a18022b56535a4d3d84363e1091f5b/ops/pebble.py#L2002), where `start_service` and similar call `wait_change` to wait for the change to complete before returning, or raise an error on failure.

That said, we could still consider making Pebble smarter about this particular case.

**Comment by r00ta** [comment]
> Whenever you call start/stop/restart/replan, Pebble returns a change ID that you can poll with [`/v1/changes/{changeID}`](https://github.com/canonical/pebble/blob/18c93cbc280de20c9e21d323fe3a8bbb340777a2/internals/daemon/api_changes.go#L173) or wait for with [`/v1/changes/{changeID}/wait`](https://github.com/canonical/pebble/blob/18c93cbc280de20c9e21d323fe3a8bbb340777a2/internals/daemon/api_changes.go#L186).

Thank you very much for the very detailed reply! This is exactly what I was looking for. We will try it as soon as we have some capacity

**Comment by benhoyt** [comment]
Thanks @r00ta. I've opened https://github.com/canonical/pebble/issues/410 to track making the "cannot start service while starting" case smarter.
