### ISSUE TITLE
Pebble should support the reuse of a container's define ENTRYPOINT or CMD

### ISSUE THREAD

**Issue by mmanciop** [canonical/pebble#42]
When writing new sidecar charms, it is convenient to reuse container images already in the wild. Unfortunately, having to specify the command to execute in the Pebble service sends developers down the rabbit whole of reconstructing what that command is. In some cases, when one has access to the Dockerfile, this is not an insurmountable burden. But things get far more complex when the only thing at hand is the Docker image itself, requiring specialized tools like [`dive`](https://github.com/wagoodman/dive) to introspect the image.

**Comment by jnsgruk** [comment]
Hey - this is a duplicate of #22 .

You can also use `docker inspect <image name>`  if you've got it pulled locally.

**Comment by mmanciop** [comment]
Duplicate of #22
