### ISSUE TITLE
ip address is not availabe or incorrect on pebble_ready

### ISSUE THREAD

**Issue by sed-i** [canonical/pebble#43]
## Environment
mickrok8s in multipass (4 cpus, 8G ram):
```
$ juju --version
2.9.0-ubuntu-amd64

$ microk8s kubectl version
Client Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.7-34+df7df22a741dbc", GitCommit:"df7df22a741dbc18dc3de3000b2393a1e3c32d36", GitTreeState:"clean", BuildDate:"2021-05-12T21:08:20Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
```

## Description
When I deploy and then add 3 units ([alertmanager](https://github.com/sed-i/alertmanager-operator/tree/feature/pebblization), in my case), occasionally the ip address is not ready.
This does not happen if I manually (slowly) add the units one by one.

## Expected vs actual
Expected: An IP address is ready (and correct) by the time pebble_ready fires.
Actual: Occasionally, when adding multiple units at once, IP address is not available (or old) when queried from within pebble_ready.

### While adding 3 units
Very consistently, the following code assigns `None` to `bind_address`, for 1-2 of the added units:
```python
relation = self.model.get_relation("replicas")
bind_address = self.model.get_binding(relation).network.bind_address
```
Similarly, `unit-get` occasionally returns an empty string under the same circumstances:
```python
bind_address = check_output(["unit-get", "private-address"]).decode().strip()
```

### When restarting the machine
I have 4 units running, and then suddenly I `sudo reboot`. When the application (alertmanager) starts up, `bind_address` returns the IP address from the _previous_ boot.

**Comment by jnsgruk** [comment]
I think this need to be opened against Operator Framework, not Pebble. This isn't related to Pebble itself, the `<container>-pebble-ready` events are emitted by the Juju Controller, and responded to by your Charm (and by extension the operator framework). :)

**Comment by benhoyt** [comment]
Closing this issue as we have canonical/operator#538
