### ISSUE TITLE
Pebble Connection Issue

### ISSUE THREAD

**Issue by addyess** [canonical/pebble#44]
Using this charm, a user reported an [issue](https://github.com/addyess/charm-splunk-k8s/issues/3) connecting to pebble socket.  Feel free to close if this has been reported

**Comment by jnsgruk** [comment]
Hmm, that looks like a sequencing/timing issue in the charm

**Comment by benhoyt** [comment]
Going to close this per above -- assumption is it's a sequencing issue with the charm.
