### ISSUE TITLE
`pebble logs -f` blocks shutdown of pebble

### ISSUE THREAD

**Issue by hpidcock** [canonical/pebble#55]
SIGINT/SIGTERM to pebble daemon while `pebble logs -f` is active does not behave as expected.

Pebble daemon waits for the `/v1/logs?follow=true` request to be cancelled.

**Comment by benhoyt** [comment]
Note that SIGINT/SIGTERM do actually initiate the shutdown process, but there's a 25 second timeout, and since the API server has open requests (`pebble logs -f`) it waits the full 25s. Thoughts on just reducing the timeout to 3s? https://github.com/canonical/pebble/pull/109

**Comment by benhoyt** [comment]
Hmmm, on second thoughts I'm not so sure about reducing this. When we forward signals to child processes ([issue](https://github.com/canonical/pebble/issues/6)) we'll want SIGINT/SIGTERM to go to the running services, and then Pebble should wait (up to) a reasonable amount of time for things like PostgreSQL to clean up and terminate. I'll think about this some more now that I'm working on forwarding of signals.
