### ISSUE TITLE
[RFE] Add Stop command to the pebble layer

### ISSUE THREAD

**Issue by phvalguima** [canonical/pebble#70]
Hi,

I am currently writing a charm for postgresql on top of k8s and I am having some issues when it comes to the stop routine.

Pebble does not allow me to choose how to stop my services, and the way it does according to the code pointed by [pebble#62](https://github.com/canonical/pebble/issues/62) is executed on [handlers.go](https://github.com/canonical/pebble/blob/78ab29be763944c083fd1ea5c64e07cd38d317cc/internal/overlord/servstate/handlers.go#L192-L203) as follows:
1. Send a SIGTERM
2. Sleep for 250 msecs
3. Send a SIGKILL

However, that is not the best way to deal with [postgresql](https://www.postgresql.org/docs/12/server-shutdown.html):
```
It is best not to use SIGKILL to shut down the server. Doing so will prevent the server from releasing shared memory and semaphores. Furthermore, SIGKILL kills the postgres process without letting it relay the signal to its subprocesses, so it might be necessary to kill the individual subprocesses by hand as well.
```

Therefore, we should have a stop command similar to the "command" on pebble layer, where we define a routine for stopping the application:
```
        pebble_layer = {
            "summary": "postgresql layer",
            "description": "pebble config layer for httpbin",
            "services": {
                "postgresql": {
                    "override": "replace",
                    "summary": "postgresql unit",
                    "command": "/usr/local/bin/docker-entrypoint.sh postgres",
                    "stopCommand": "pg_ctl stop -D /var/lib/postgresql/data", <<<-----------
                    "startup": "enabled"
                }
            },
        }
```

That command would be executed whenever the operator issues a stop action to the pebble.

Right now, the way I am dealing with it is by manually stopping Postgresql services before calling the actual service stop:
```
                # Stop service so we can run the replication
                self._stop_app()
                # Run the stop to inform pebble
                container.stop("postgresql")
```

**Comment by benhoyt** [comment]
We probably won't add `stopCommand` as a customization, but I think we can make some changes here that will help solve this problem. We have a couple of options:

1) Make the delay between trying SIGTERM and sending SIGKILL configurable. As the docs you linked to show, PostgreSQL does try to respond gracefully to SIGTERM, waiting for existing queries to finish. But that may take some time, especially if there are long-running queries. Would it help to add a config option like `sigkill-delay`, which would default to 250ms, but be customizable? In the case of PostgreSQL you could set it to something like 5 seconds.
2) There's also SIGINT, which initiates PostgreSQL's "fast shutdown" mode, not quite as graceful as it cancels existing queries, but still safe. So alternatively, we could add a `stop-signal` service config option, which defaults to SIGTERM but you could set to SIGINT for this case. We'd still probably want `sigkill-delay` configurable, though.
3) We're also planning to add the ability to send arbitrary signals to any active process. With that feature, you'd do something like this:

```
container.send_signal(SIGINT, 'postgresql')
time.sleep(5)
container.stop('postgresql')
```

Thoughts on the above? I'm tempted to say we should just wait for the send-signals feature.

**Comment by phvalguima** [comment]
Hi @benhoyt, in my view, ```send_signal``` is a valid alternative as long as ```doStop``` and ```container.stop()``` do not fail if target process not found.

I really would like to avoid SIGKILL as much as possible. I was looking into other stateful apps and I can see how SIGKILL is a common problem across them, e.g. [mongodb](https://docs.mongodb.com/manual/tutorial/manage-mongodb-processes/#sigkill) or [kafka - graceful shutdown](https://kafka.apache.org/documentation/#basic_ops_restarting).

My suggestion is to (1) tweak ```doStop``` (or ```container.stop()```) in such a way that it can be called without the target process existing; and (2) yes, wait for send_signal feature. That means, I will have the option of doing:

```
container.send_signal(SIGINT, 'postgresql')
time.sleep(5)
self._check_if_psql_really_shutdown() # method to verify if psql is running and, if yes, take a decision of what to do next
container.stop('postgresql') # just to inform pebble we are stopping, PID does not exist anymore
```

**Comment by benhoyt** [comment]
Thanks. Yeah, I think that's a good approach (once `send_signal` is ready). Given this is planned, I'll close this issue in favour of https://github.com/canonical/pebble/issues/76

In addition, with one-shot commands having just landed (and will land in Python Operator Framework soon), you'll be able to run things like `kill -SIGINT` on the remote machine using Pebble's exec API.
