### ISSUE TITLE
Files API: add way to create symlinks (and discuss symlink handling)

### ISSUE THREAD

**Issue by benhoyt** [canonical/pebble#75]
Per https://bugs.launchpad.net/juju/+bug/1945941, it would be good to have a Pebble way to create symlinks using the files API. However, we should also think through and discuss how symlinks work in the files API more broadly, e.g., how do `push` and `pull` interact with symlinks (eg: does `pull` read the link or the contents of the file at the link), and so on. So this may need a small spec.

**Comment by rwcarlsen** [comment]
It might be nice to have the pebble file listing API put symlink target path info into the file info response/result.  That would give us some flexibility on the OF side to deal with these issues.

**Comment by benhoyt** [comment]
This has not been requested at all -- I'm just going to go ahead and close this as not planned. We can always revisit if it turns out there's a need.
