### ISSUE TITLE
Allow to specify working directory for exec commands

### ISSUE THREAD

**Issue by mmanciop** [canonical/pebble#82]
When executing a command, especially within containers that do not have a shell (e.g., Distroless), it is very useful to be able to optionally specify the working directory for running the command. When a working directory is specify, but it does exist or the resolved file handle is not a directory, the exec command should fail.

**Comment by jnsgruk** [comment]
I didn't realise this when we discussed last week - but I think this is already supported: https://ops.readthedocs.io/en/latest/#ops.pebble.Client.exec

**Comment by benhoyt** [comment]
Yep, this is already supported via the `working_dir` parameter. (Sorry for the late reply - was on leave for the last couple of work days.)
